### ISSUE TITLE
brackets-beautify adding extra blank lines before head, body, /html tags

### ISSUE THREAD

**Issue by jbwCode** [Hirse/brackets-beautify#10]
This is a great extension, but I was getting annoyed by this behavior. This is apparently the default option for js-beautify with html. 

There was no option in the "default.jsbeautifyrc" file for this option, so I added

"extra_liners": []

to the "html" section of "default.jsbeautifyrc"  within my Brackets extensions folder, based on the documentation for js-beautify. Works like a charm!

https://github.com/beautify-web/js-beautify

-E, --extra_liners    List of tags (defaults to [head,body,/html] that should have an extra newline before them.

**Comment by Hirse** [comment]
Happy you like it.

As your problem seems to be solved, I am going to close this.
