### ISSUE TITLE
Why newline_between_rules inside a @media rule does nothing?

### ISSUE THREAD

**Issue by ErickPetru** [Hirse/brackets-beautify#11]
I have already put `"newline_between_rules": true` inside my `.jsbeautifyrc` file.

It works well for all rules outside of groups, but inside groups (like `@media`) the children rules stay together.

I believe it's some bug with the `beautify-css.js` file, but I couldn't find a GitHub project for itself. Is there any solution to it?

**Comment by Hirse** [comment]
It is the same library for all beautify files:
[js-beautify](https://github.com/beautify-web/js-beautify)

**Comment by ErickPetru** [comment]
Thank you @Hirse, so I created an issue there (https://github.com/beautify-web/js-beautify/issues/769).

**Comment by Hirse** [comment]
Alright, I am going to close this issue, but also going to keep an eye on the one at the library.
