### ISSUE TITLE
Added Space on CSS Selector

### ISSUE THREAD

**Issue by ghost** [Hirse/brackets-beautify#12]
When beautifying an SCSS file I have, the plugin always adds a space in this selector:

```
&:not(: first-child)
```

I remove the space, save the file again, and it adds the space again. Tying this with an SCSS compiler in Brackets, the compiler fails because of the space.

If you need any more information, I'll be happy to provide it.

Thanks.
~ Griff

**Comment by Hirse** [comment]
I am sorry you are having this problem.
Unfortunately this is an issue of the used [library](https://github.com/beautify-web/js-beautify), so I am unable to fix it unless they do.
Please open an issue on their GitHub page.

**Comment by ghost** [comment]
Thank you for your response. I have opened a ticket on their GitHub page as well.

https://github.com/beautify-web/js-beautify/issues/770
