### ISSUE TITLE
Ctrl-Shift-L On Linux

### ISSUE THREAD

**Issue by Hippyjake** [Hirse/brackets-beautify#2]
On Linux I can not use the keyboard shortcut. If I remember right, long ago. The original allowed for this but has not for some time. Its also bork in other ways, but you know that ;)  So far your fork has fixed all the issues I have had, save the keyboard shortcut.
Anything I can do to help Ill jump right in!

**Comment by Hirse** [comment]
I am on Windows (at least for now) so I didn't test other OS.

I have made a change right now, please have a look if that fixes it for you.
If not, please check the Developer Tools Console for any KeyBinding errors.

**Comment by Hippyjake** [comment]
After some testing I assume the fix works, but is conflicting with "split section into lines" in the edit menu. This is a default keybinding. The stable version does not throw the conflicting error.

Thanks for your quick response.

**Comment by Hirse** [comment]
On Windows that is `Ctrl+Alt+L`, so there is no conflict for me.
Should I use a different key binding for Linux then?

**Comment by Hippyjake** [comment]
And the winning combo is

``` js
    var keyBindings = [
        {
            key: 'Ctrl-Shift-L',
            platform: 'win'
        }, {
            key: 'Cmd-Shift-L',
            platform: 'mac'
        }, {
            key: 'Ctrl-Alt-L'
        }
    ];
```

Thank you!

**Comment by Hippyjake** [comment]
On second thought. I just hope that wont lock peoples desktop sessions, some might. "Ctrl-Alt-B" Might be a good alternative

**Comment by Hirse** [comment]
Yes, that seems to be the case.
I think I will go with 

``` js
var keyBindings = [
        {
            key: 'Ctrl-Shift-L',
            platform: 'win'
        }, {
            key: 'Ctrl-Alt-B',
            platform: 'win'
        }, {
            key: 'Cmd-Shift-L',
            platform: 'mac'
        }, {
            key: 'Ctrl-Alt-B'
        }
    ];
```

for now, therefore giving Windows user the choice.

And finally, you could still overwrite that in your user-key-mapping.

**Comment by Hippyjake** [comment]
Awesome thank you so much!

**Comment by Hirse** [comment]
I have released a new version, could you make sure it works for you?

**Comment by Hippyjake** [comment]
All good here
