### ISSUE TITLE
Messing with wordpress code

### ISSUE THREAD

**Issue by dawidadach** [Hirse/brackets-beautify#5]
Hi, I really apprecatie your extension however when try to using this to develop wordpress theme after hiting Control Shift L its messing up with function i.e. 

Before:
        <?php 
$args = array (
'theme_location' => 'primary');
        ?>

After:
    <?php $args=a rray ( 'theme_location'=> 'primary'); ?>

So its adding extra space in "array" word.

**Comment by Hirse** [comment]
Yes, I have read about this kind of issue before.
The reason for this is that the [library](https://github.com/beautify-web/js-beautify) I am using [doesn't support PHP](https://github.com/beautify-web/js-beautify/issues/714). I was under the impression that they at least [fixed breaking PHP](https://github.com/beautify-web/js-beautify/issues/490), but apparently that is not the case. Please open an issue with them regarding the actual formatting.

Regarding this extension, I can only advise you to not use it for `.php` files at the moment and deactivate _Beautify-on-Save_ for those by adding this to the `brackets.json`:

``` json
{
    "language": {
        "php": {
            "hirse.beautify.onSave": false
        }
    }
}
```
