### ISSUE TITLE
Missing indent when declaring multiple methods

### ISSUE THREAD

**Issue by alexandradeas** [Hirse/brackets-beautify#9]
In screenshot the indentation is slightly wrong on the first method (.when) in a list when declaring multiple methods to an object.

![screenshot from 2015-07-23 20 27 17](https://cloud.githubusercontent.com/assets/12813479/8860087/49ae5da0-3179-11e5-92c8-19424987c306.png)

**Comment by Hirse** [comment]
Can you please test the beautification of your file with the library directly?
You can use their website here: http://jsbeautifier.org/

If the issue persists, please [open an issue with them](https://github.com/beautify-web/js-beautify/issues/new).
